### ISSUE TITLE
copy editing

### ISSUE THREAD

**Issue by logemerson** [learn-co-curriculum/js-object-oriented-classes-readme#6]
<img width="855" alt="screen shot 2017-11-06 at 12 30 07 pm" src="https://user-images.githubusercontent.com/28125427/32455297-d5b6f6d6-c2ef-11e7-9b0d-c10e83eff167.png">
In the above image, the highlighted "shares has" ought to be _either_ "shares" or "has".

<img width="854" alt="screen shot 2017-11-06 at 12 30 48 pm" src="https://user-images.githubusercontent.com/28125427/32455306-dad3068c-c2ef-11e7-9f6b-6c1267724976.png">
In the above image, the highlighted "that" ought to be "that's" or "that is".

**Comment by cjbrock** [comment]
That was definitely some special grammar construction. Thank you for finding it for us!

// <3 Corinna
