### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by jerrybennett** [learn-co-curriculum/js-object-oriented-classes-readme#7]
in the last section of code, regarding using 'super,' these are the last few lines:
 ```
19
20  tom.sayHello()
21  // Hello, my name is fred
22  // hello
```
`tom.sayHello()` returns:
`// Hello, my name is tom`
in the console.

not `// Hello, my name is fred`

**Comment by cjbrock** [comment]
Seems like Tom's been drinking a bit there! I've changed it. Thanks!

// <3 Corinna
