### ISSUE TITLE
Typo to be fixed 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-object-oriented-classes-readme#9]
Here, we've extended, or inherited from User when creating the new Teacher class. We also added a new method teachMath that available to Teacher objects but is not available to User objects. We can override an inherited method simply by defining another method with the same name.

in middle line: 
that available
should be: that's availabe or that is available.

**Comment by cjbrock** [comment]
Thank you! Verbs tend to help sentence structure out a bit. 

// <3 Corinna
